package com.baro.constants

// Contains the App Codes used to pass intents
enum class AppCodes(val code: Int) {
    CAMERA_ROLL_SELECTION(100), GALLERY_SELECTION(101), FORWARD_SLIDE(102), BACKWARDS_SLIDE(103), NO_CHANGE_SLIDE(105), COURSE_SAVED(106), COURSE_NOT_SAVED(107), UPDATE_COURSE_META_DATA(107), CREATE_COURSE_META_DATA(108);

}