package com.baro.constants

// Contains the App Codes used to pass intents
enum class AppCodes(val code: Int) {
    CAMERA_ROLL_SELECTION(100),
    GALLERY_SELECTION(101),
    FORWARD_SLIDE(102),
    BACKWARDS_SLIDE(103),
    NO_CHANGE_SLIDE(105),
    WIFIP2P_CONNECTED(106),
    WIFIP2P_NOT_CONNECTED(107),
    WIFIP2P_PEER_DISCOVERING(108),
    WIFIP2P_NOT_PEER_DISCOVERING(109),
    WIFIP2P_PEERS_DISCOVERED(110);
}